import { type NextPage } from "next";
import Head from "next/head";
import Editor from "@monaco-editor/react";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import axios from "axios";
import Swal from 'sweetalert2'
import withReactContent from 'sweetalert2-react-content'

const Home: NextPage = () => {
  const { query } = useRouter();
  const [code, setCode] = useState("");
  const [loading, setLoading] = useState(true);
  const [lang, setLang] = useState("javascript");
  const MySwal = withReactContent(Swal);

  useEffect(() => {
    axios
      .get(`/api/${query["id"] as string}`)
      .then((res) => {
        // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
        setCode(res.data?.content as string);
        setLoading(false);
      })
      .catch(() => console.log("err"));
  }, [query]);

  return (
    <>
      <Head>
        <title>Codeshare</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav className="flex items-center justify-between bg-slate-200 p-4">
          <div className="flex">
            <h1 className="mr-2 font-bold">Codeshare</h1>
            <select
              className="mr-3 cursor-pointer appearance-none text-slate-400"
              onChange={(e) => setLang(e.target.value)}
            >
              <option value="javascript" className="text-black">
                javascript
              </option>
              <option value="typescript" className="text-black">
                typescript
              </option>
              <option value="python" className="text-black">
                python
              </option>
              <option value="html" className="text-black">
                html
              </option>
              <option value="css" className="text-black">
                css
              </option>
              <option value="rust" className="text-black">
                rust
              </option>
              <option value="java" className="text-black">
                java
              </option>
              <option value="csharp" className="text-black">
                C#
              </option>
              <option value="cpp" className="text-black">
                C++
              </option>
              <option value="json" className="text-black">
                json
              </option>
              <option value="markdown" className="text-black">
                markdown
              </option>
              <option value="vb" className="text-black">
                Visual Basic
              </option>
              <option value="scss" className="text-black">
                SCSS
              </option>
              <option value="less" className="text-black">
                LESS
              </option>
              <option value="php" className="text-black">
                php
              </option>
              <option value="batch" className="text-black">
                batch
              </option>
              <option value="lua" className="text-black">
                lua
              </option>
              <option value="ruby" className="text-black">
                ruby
              </option>
              <option value="coffeescript" className="text-black">
                coffeescript
              </option>
              <option value="powershell" className="text-black">
                powershell
              </option>
            </select>
          </div>

          <div className="flex">
            <a
              className="mr-3 cursor-pointer text-gray-700 hover:text-gray-900"
              onClick={() => {
                window.location.href = `/?clone=${query["id"] as string}`;
              }}
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="icon icon-tabler icon-tabler-device-floppy h-7 w-7 hover:scale-105"
                width="44"
                height="44"
                viewBox="0 0 24 24"
                stroke-width="1.5"
                stroke="#000000"
                fill="none"
                stroke-linecap="round"
                stroke-linejoin="round"
              >
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <path d="M9 7h-3a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2 -2v-3" />
                <path d="M9 15h3l8.5 -8.5a1.5 1.5 0 0 0 -3 -3l-8.5 8.5v3" />
                <line x1="16" y1="5" x2="19" y2="8" />
              </svg>
            </a>

            <a
              className="mr-3 cursor-pointer text-gray-700 hover:text-gray-900"
              onClick={() => {
                void navigator.clipboard.writeText(code);
                void MySwal.fire({
                    title: <p>Copied Successfully!</p>,
                    showConfirmButton: false,
                    icon: "success"
                  })
              }}
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="icon icon-tabler icon-tabler-device-floppy h-7 w-7 hover:scale-105"
                width="44"
                height="44"
                viewBox="0 0 24 24"
                stroke-width="1.5"
                stroke="#000000"
                fill="none"
                stroke-linecap="round"
                stroke-linejoin="round"
              >
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <rect x="8" y="8" width="12" height="12" rx="2" />
                <path d="M16 8v-2a2 2 0 0 0 -2 -2h-8a2 2 0 0 0 -2 2v8a2 2 0 0 0 2 2h2" />
              </svg>
            </a>
          </div>
        </nav>
        {loading ? (
          <div className="flex min-h-screen flex-row items-center justify-center">
            Loading...
          </div>
        ) : (
          <Editor
            height="90vh"
            className="mt-3 h-screen w-screen"
            language={lang}
            value={code}
            options={{ readOnly: true }}
          />
        )}
      </main>
    </>
  );
};

export default Home;
