import { type NextPage } from "next";
import Head from "next/head";
import Editor from "@monaco-editor/react";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import axios from "axios";

const Home: NextPage = () => {
  const { query } = useRouter();
  const [code, setCode] = useState("");
  const [lang, setLang] = useState("javascript");

  useEffect(() => {
    axios
      .get(`/api/${query["id"] as string}`)
      .then((res) => {
        // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
        setCode(res.data?.content as string);
      })
      .catch(() => console.log("err"));
  }, [query]);

  return (
    <>
      <Head>
        <title>Codeshare</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav className="flex items-center justify-between bg-slate-200 p-4">
          <div className="flex">
            <h1 className="mr-2 font-bold">Codeshare</h1>
            <select
              className="mr-3 cursor-pointer appearance-none text-slate-400"
              onChange={(e) => setLang(e.target.value)}
            >
              <option value="javascript" className="text-black">
                javascript
              </option>
              <option value="typescript" className="text-black">
                typescript
              </option>
              <option value="python" className="text-black">
                python
              </option>
              <option value="html" className="text-black">
                html
              </option>
              <option value="css" className="text-black">
                css
              </option>
              <option value="rust" className="text-black">
                rust
              </option>
              <option value="java" className="text-black">
                java
              </option>
              <option value="csharp" className="text-black">
                C#
              </option>
              <option value="cpp" className="text-black">
                C++
              </option>
              <option value="json" className="text-black">
                json
              </option>
              <option value="markdown" className="text-black">
                markdown
              </option>
              <option value="vb" className="text-black">
                Visual Basic
              </option>
              <option value="scss" className="text-black">
                SCSS
              </option>
              <option value="less" className="text-black">
                LESS
              </option>
              <option value="php" className="text-black">
                php
              </option>
              <option value="batch" className="text-black">
                batch
              </option>
              <option value="lua" className="text-black">
                lua
              </option>
              <option value="ruby" className="text-black">
                ruby
              </option>
              <option value="coffeescript" className="text-black">
                coffeescript
              </option>
              <option value="powershell" className="text-black">
                powershell
              </option>
            </select>
          </div>
        </nav>
        <Editor
          height="90vh"
          className="h-screen w-screen"
          language={lang}
          defaultValue={code}
        />
      </main>
    </>
  );
};

export default Home;
